### ISSUE TITLE
Object  has no method 'updateCollectionForRelationship'

### ISSUE THREAD

**Issue by mafcm** [sabymike/mongoose-relationship#10]
Hi,

It's my first time using mongoose. I built relationship between two model **User** and **Post** and I get an error.

I was running this code
```
User.findOne({ _id : "53f57c1aeb844b2c068b4569" }, function(err, u) {
	if (err) {
		handleError(err);
	}

	if (u) {
		console.log(u);
		console.log(u._id);

		new Post({
			author : u
		}).save(function(err, p) {
			if (err) {
				handleError(err);
			}
			console.log(p);
		});
	}
});
```
when I get this error 
```
TypeError: Object { author: 53f57c1aeb844b2c068b4569,
  _id: 548fc0c38615a22816a28be7,
  items: [],
  updated_at: Tue Dec 16 2014 06:18:59 GMT+0100 (WAT),
  created_at: Tue Dec 16 2014 06:18:59 GMT+0100 (WAT),
  description: 'Description',
  title: 'Title' } has no method 'updateCollectionForRelationship'
    at /usr/local/lib/node_modules/mongoose-relationship/index.js:129:26
    at /usr/local/lib/node_modules/mongoose-relationship/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/mongoose-relationship/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/usr/local/lib/node_modules/mongoose-relationship/node_modules/async/lib/async.js:110:9)
    at model.<anonymous> (/usr/local/lib/node_modules/mongoose-relationship/index.js:125:15)
    at _next (/usr/local/lib/node_modules/mongoose/node_modules/hooks/hooks.js:50:30)
    at fnWrapper (/usr/local/lib/node_modules/mongoose/node_modules/hooks/hooks.js:159:8)
    at complete (/usr/local/lib/node_modules/mongoose/lib/document.js:986:5)
    at /usr/local/lib/node_modules/mongoose/lib/document.js:977:20
```

How to solve it please ?

**Comment by sabymike** [comment]
Sorry for the extremely late response. If you are still having this problem I would have to see your Schema declarations for Post and User to understand what is happening.

**Comment by anton164** [comment]
I'm experiencing the same problem, here are my Schema declarations:
```javascript
var UserSchema = new Schema({
  name: String,
  email: {
    type: String,
    lowercase: true
  },
  role: {
    type: String,
    default: 'user'
  },
  project: {
    type: Schema.ObjectId,
    ref: 'Project',
    childPath: 'users'
  },
  hashedPassword: String,
  provider: String,
  salt: String,
});

var timestamps = require('mongoose-timestamp');
UserSchema.plugin(timestamps);
var relationship = require("mongoose-relationship");
UserSchema.plugin(relationship, {
  relationshipPathName: 'project'
});
```

```javascript
var ProjectSchema = new Schema({
  name: String,
  accounts: [{
    type: Schema.ObjectId,
    ref: 'Account'
  }],
  users: [{
    type: Schema.ObjectId,
    ref: 'User'
  }]
});
var timestamps = require('mongoose-timestamp');
ProjectSchema.plugin(timestamps);
```

**Comment by anton164** [comment]
Ah, just figured this one out, I just started using the http://github.com/DaftMonk/generator-angular-fullstack as a base for my project. What I didn't include above, in the UserSchema paste, was that they override the UserSchema.methods further down in the file.

Rewrote to using UserSchema.method('...'), and it works as a charm :)
